driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: bento/centos-6.7
  - name: bento/centos-7.2
  - name: bento/ubuntu-14.04
  - name: bento/ubuntu-16.04
  - name: bento/fedora-21
  - name: bento/debian-7.10
  - name: bento/debian-8.4

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[php]
      - recipe[php-fpm]
      - recipe[tideways::install]
      - recipe[tideways::configure]
