name 'tideways'
version '0.4.2'
maintainer 'Rupert Jones'
maintainer_email 'rjones@inviqa.com'
license 'Apache 2.0'
description 'Install and configure tideways daemon and PHP extension'

depends 'yum'
depends 'apt'
depends 'php'
