name "tideways"
version "0.2.0"
maintainer "Rupert Jones"
maintainer_email "rjones@inviqa.com"
license "Apache 2.0"
description "Install and configure tideways daemon and PHP extension"
depends "apt"
depends "yum"
depends "php-fpm"
depends "httpd"
