name 'tideways'
version '0.4.2'
maintainer 'Rupert Jones'
maintainer_email 'rjones@inviqa.com'
license 'Apache 2.0'
description 'Install and configure tideways daemon and PHP extension'
issues_url 'https://github.com/inviqa/tideways-cookbook/issues'
source_url 'https://github.com/inviqa/tideways-cookbook'

supports 'centos'
supports 'debian'
supports 'fedora'
supports 'rhel'
supports 'ubuntu'

depends 'yum'
depends 'apt'
depends 'php'
